# Generated by Django 5.0 on 2023-12-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_new_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_img',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='news/'),
        ),
    ]
